using System;
using System.Globalization;
using System.IO;
using System.Text.RegularExpressions;

namespace Regard.Backend.Services
{
    /// <summary>
    /// A sidecar subtitle file found next to a downloaded video, e.g. "&lt;prefix&gt;.en.vtt".
    ///
    /// Only vtt and srt are ever produced here: a browser &lt;track&gt; consumes WebVTT only, and srt is the
    /// one other format we can convert losslessly. yt-dlp's "best" sub-format can also yield json3/srv3,
    /// which are simply not listed rather than served as something the player can't parse.
    /// </summary>
    public class SubtitleFile
    {
        /// <summary>Absolute path on disk.</summary>
        public string Path { get; set; }

        /// <summary>The language tag exactly as yt-dlp wrote it into the filename ("en", "ro", "en-orig").</summary>
        public string Lang { get; set; }

        /// <summary>Lower-case extension without the dot: "vtt" or "srt".</summary>
        public string Format { get; set; }

        /// <summary>
        /// True when the cues look machine-generated. See <see cref="SubtitleProbe"/> — this is sniffed
        /// from the file, not derived from the name, because yt-dlp writes manual and automatic captions
        /// to identical filenames.
        /// </summary>
        public bool AutoGenerated { get; set; }

        /// <summary>
        /// The language tag between the output prefix and the extension, or null when the file isn't a
        /// subtitle sidecar.
        ///
        /// Matching is anchored on the prefix so that "&lt;prefix&gt;.info.json", "&lt;prefix&gt;.f315.webm.part",
        /// "&lt;prefix&gt;.mp4" and "&lt;prefix&gt;-thumb.jpg" are all rejected — the last of those matters because
        /// VideoStorageService.BelongsTo deliberately returns it despite the dash, so a blind
        /// Substring(prefix.Length + 1) would either misparse it or throw on a shorter name.
        /// </summary>
        private static readonly Regex LangAndExt = new Regex(
            @"^(?<lang>[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\.(?<ext>vtt|srt)$",
            RegexOptions.Compiled | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        public static SubtitleFile TryParse(string fullPath, string filePrefix)
        {
            string fileName = System.IO.Path.GetFileName(fullPath);
            string dotted = filePrefix + ".";
            if (!fileName.StartsWith(dotted, StringComparison.Ordinal))
                return null;

            var match = LangAndExt.Match(fileName.Substring(dotted.Length));
            if (!match.Success)
                return null;

            return new SubtitleFile
            {
                Path = fullPath,
                Lang = match.Groups["lang"].Value,
                Format = match.Groups["ext"].Value.ToLowerInvariant(),
            };
        }

        /// <summary>
        /// Human-readable name for the picker.
        ///
        /// Deliberately not a try/catch around CultureInfo: on ICU (what we actually run on, both locally
        /// and in the aspnet:10.0 image) GetCultureInfo never throws for these tags — it happily invents
        /// "English (Orig)" for "en-orig" and "Invariant Language (Invariant Country)" for "und". So the
        /// -orig suffix is peeled off explicitly and an invariant/unnamed result falls back to the raw tag.
        /// </summary>
        public static string LabelFor(string lang, bool autoGenerated)
        {
            string tag = lang;
            bool original = false;

            if (tag.EndsWith("-orig", StringComparison.OrdinalIgnoreCase))
            {
                original = true;
                tag = tag.Substring(0, tag.Length - "-orig".Length);
            }

            string name = tag;
            try
            {
                var culture = CultureInfo.GetCultureInfo(tag);
                if (culture.Name.Length > 0 && !string.IsNullOrWhiteSpace(culture.DisplayName))
                    name = culture.DisplayName;
            }
            catch (CultureNotFoundException)
            {
                // Malformed tag — keep the raw string.
            }

            if (original)
                name += " (original)";

            if (autoGenerated)
                name += " (auto-generated)";

            return name;
        }
    }

    /// <summary>
    /// Tells machine-generated captions from human-authored ones by looking at the cues.
    ///
    /// yt-dlp gives no filename hint: with --write-subs and --write-auto-subs both on it writes whichever
    /// it got to "&lt;prefix&gt;.&lt;lang&gt;.vtt" either way. But YouTube's ASR output carries per-word timing tags
    /// inside the cue text ("While&lt;00:00:00.560&gt;&lt;c&gt; waiting&lt;/c&gt;") and human-written tracks never do.
    /// Checked against all 22 sidecars in the dev library: the split lands exactly where it should, with
    /// Kurzgesagt's English (hand-written) on one side and its auto-translated Romanian on the other.
    ///
    /// The signal does not survive yt-dlp's --convert-subs srt, so srt files are reported as not
    /// auto-generated rather than guessed at.
    /// </summary>
    public static class SubtitleProbe
    {
        // Measured: the first tag appears at byte 96-514 across every file in the library, so a small
        // window is plenty. Kept well above that so an unusually long header can't cause a false negative.
        private const int ProbeBytes = 8 * 1024;

        private static readonly Regex WordTimingTag = new Regex(
            @"<\d{2}:\d{2}:\d{2}\.\d{3}>",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        public static async System.Threading.Tasks.Task<bool> IsAutoGenerated(string path, string format)
        {
            if (!string.Equals(format, "vtt", StringComparison.OrdinalIgnoreCase))
                return false;

            try
            {
                using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite,
                                                  bufferSize: 4096, useAsync: true);
                var buffer = new byte[ProbeBytes];
                int read = await stream.ReadAsync(buffer, 0, buffer.Length);
                if (read <= 0)
                    return false;

                // The tag is pure ASCII, so decoding a possibly-truncated UTF-8 tail can't create or
                // destroy a match.
                string head = System.Text.Encoding.UTF8.GetString(buffer, 0, read);
                return WordTimingTag.IsMatch(head);
            }
            catch (IOException)
            {
                return false;
            }
        }
    }
}
