using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MimeMapping;
using Regard.Backend.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Regard.Backend.Services
{
    public class VideoStorageService : IVideoStorageService
    {
        private readonly ILogger log;
        private readonly StorageManager storageManager;

        private string RootPath => storageManager.DownloadDirectory;

        public VideoStorageService(ILogger<VideoStorageService> log,
                                   StorageManager storageManager)
        {
            this.log = log;
            this.storageManager = storageManager;
        }

        private string GetPath(Video video)
        {
            return Path.Combine(RootPath, video.DownloadedPath);
        }

        public async IAsyncEnumerable<string> GetFiles(Video video)
        {
            if (video.DownloadedPath != null)
            {
                await foreach (var file in GetFilesAt(video.DownloadedPath))
                    yield return file;
            }
        }

        /// <summary>
        /// Files whose name starts with the given extension-less path prefix, which is how a download's
        /// outputs are grouped (media, .part, .info.json, thumbnail, subtitles, NFO).
        ///
        /// Exists separately from <see cref="GetFiles"/> because that one keys off
        /// <see cref="Video.DownloadedPath"/>, which is written only when a download *succeeds*. A
        /// download that died midway therefore leaves a .part behind that GetFiles cannot see — so
        /// a forced re-download has to sweep the freshly-resolved output path as well.
        /// </summary>
        public async IAsyncEnumerable<string> GetFilesAt(string outputPathPrefix)
        {
            if (string.IsNullOrEmpty(outputPathPrefix))
                yield break;

            var path = Path.Combine(RootPath, outputPathPrefix);
            var dir = Path.GetDirectoryName(path);
            var filePrefix = Path.GetFileName(path);

            if (string.IsNullOrEmpty(filePrefix) || !Directory.Exists(dir))
                yield break;

            foreach (var file in await Task.Run(() => Directory.GetFiles(dir)))
            {
                string fileName = Path.GetFileName(file);
                if (BelongsTo(fileName, filePrefix))
                    yield return file;
            }
        }

        /// <summary>
        /// Whether a filename is one of the outputs for an extension-less path prefix.
        ///
        /// The boundary matters: a bare StartsWith would make "Foo" match "Foo (Part 2).mp4", so
        /// re-downloading or deleting one video would take a sibling's files with it.
        ///
        /// Nearly every output is the prefix followed by a dot ("<name>.mp4", "<name>.en.vtt",
        /// "<name>.f315.webm.part", "<name>.info.json", "<name>.nfo"). The one exception is the Jellyfin
        /// artwork, which DownloadVideoJob.WriteEpisodeMetadata renames to "<name>-thumb.jpg" with a dash
        /// — miss that and every re-download orphans a thumbnail. The trailing dot in "-thumb." keeps it
        /// precise, so a sibling actually named "<name>-thumbnail…" is still safe.
        ///
        /// Titles ending in a dot work unchanged: the prefix carries the dot and the file simply has two.
        /// </summary>
        private static bool BelongsTo(string fileName, string filePrefix)
        {
            return fileName.Equals(filePrefix, StringComparison.Ordinal)
                || fileName.StartsWith(filePrefix + ".", StringComparison.Ordinal)
                || fileName.StartsWith(filePrefix + "-thumb.", StringComparison.Ordinal);
        }

        /// <summary>
        /// Sidecar subtitle files for a downloaded video, with their language and provenance resolved.
        ///
        /// Shares GetFiles' enumeration (and therefore BelongsTo's prefix rule) so a title containing a
        /// slash — which puts the output prefix inside a nested directory, and this library has one —
        /// resolves the same way it does everywhere else.
        /// </summary>
        public async Task<IReadOnlyList<SubtitleFile>> GetSubtitleFiles(Video video)
        {
            var result = new List<SubtitleFile>();
            if (video.DownloadedPath == null)
                return result;

            string filePrefix = Path.GetFileName(Path.Combine(RootPath, video.DownloadedPath));
            if (string.IsNullOrEmpty(filePrefix))
                return result;

            await foreach (var file in GetFiles(video))
            {
                var subtitle = SubtitleFile.TryParse(file, filePrefix);
                if (subtitle == null)
                    continue;

                subtitle.AutoGenerated = await SubtitleProbe.IsAutoGenerated(subtitle.Path, subtitle.Format);
                result.Add(subtitle);
            }

            return result;
        }

        public async Task<string> FindVideoFile(Video video)
        {
            await foreach (var file in GetFiles(video))
            {
                string mime = MimeUtility.GetMimeMapping(file);
                if (mime.StartsWith("video"))
                    return file;
            }

            return null;
        }

        public async Task<bool> VerifyIsDownloaded(Video video)
        {
            return (await FindVideoFile(video)) != null;
        }

        /// <summary>Deletes every file sitting at the given output-path prefix. Returns how many went.</summary>
        public async Task<int> DeleteAt(string outputPathPrefix)
        {
            int deleted = 0;
            await foreach (var file in GetFilesAt(outputPathPrefix))
            {
                try
                {
                    await Task.Run(() => File.Delete(file));
                    log.LogInformation("Deleted file at {0}: {1}", outputPathPrefix, file);
                    deleted++;
                }
                catch (Exception ex)
                {
                    // Don't abort the sweep: one undeletable file (locked, permissions) shouldn't stop
                    // the rest from going, and the caller decides what a partial sweep means.
                    log.LogWarning(ex, "Could not delete {0}", file);
                }
            }
            return deleted;
        }

        public async Task Delete(Video video)
        {
            await foreach (var file in GetFiles(video))
            {
                await Task.Run(() => File.Delete(file));
                log.LogInformation("Deleted file for video {0}: {1}", video, file);
            }
        }

        public async Task<long> CalculateSize(Video video)
        {
            return await GetFiles(video)
                .Select(file => new FileInfo(file).Length)
                .SumAsync();
        }

        public async Task<string> GetMimeType(Video video)
        {
            var videoFile = await FindVideoFile(video);
            return (videoFile != null) ? MimeUtility.GetMimeMapping(videoFile) : null;
        }

        public async Task<Stream> Open(Video video)
        {
            var videoFile = await FindVideoFile(video);
            return (videoFile != null) ? File.OpenRead(videoFile) : null;
        }
    }
}
