/* THIS FILE IS AUTOGENERATED DO NOT EDIT
 *
 * This file is autogenerated from Preferences.csv. 
 * If you want to add a new user interface coordinate 
 * do so in the CSV file then rebuild.
 */
using Regard.Model;

namespace Regard.Backend.Services
{
    public static class Preferences
    {
        /// <summary>
        /// Indicates if the first time setup was performed.
        /// </summary>
        public static readonly PreferenceDefinition<bool> Server_Initialized = new PreferenceDefinition<bool>(
            false,
            "server.initialized",
            null,
            null,
            0
        );

        /// <summary>
        /// Allow user registrations from the frontend.
        /// </summary>
        public static readonly PreferenceDefinition<bool> Server_AllowRegistrations = new PreferenceDefinition<bool>(
            true,
            "server.allow_registrations",
            "AllowRegistrations",
            "REGARD_ALLOW_REGISTRATIONS",
            0
        );

        /// <summary>
        /// Send debugging information to the frontend
        /// </summary>
        public static readonly PreferenceDefinition<bool> Server_Debug = new PreferenceDefinition<bool>(
            false,
            "server.debug",
            "Debug",
            "REGARD_DEBUG",
            0
        );

        /// <summary>
        /// If enabled, videos will be downloaded automatically
        /// </summary>
        public static readonly PreferenceDefinition<bool> Subscriptions_AutoDownload = new PreferenceDefinition<bool>(
            true,
            "subscriptions.auto_download",
            "Subscriptions:AutoDownload",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Order in which to download videos
        /// </summary>
        public static readonly PreferenceDefinition<VideoOrder> Subscriptions_DownloadOrder = new PreferenceDefinition<VideoOrder>(
            VideoOrder.Newest,
            "subscriptions.download_order",
            "Subscriptions:DownloadOrder",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Maximum number of downloaded videos to keep per subscription (-1 = no limit). This limit only applies to the automatic downloader, but the user can manually download more videos.
        /// </summary>
        public static readonly PreferenceDefinition<int> Subscriptions_MaxCount = new PreferenceDefinition<int>(
            3,
            "subscriptions.max_count",
            "Subscriptions:MaxCount",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Maximum size a subscription can take on disk in MB (-1 = no limit). This limit only applies to the automatic downloader, but the user can manually download more videos.
        /// </summary>
        public static readonly PreferenceDefinition<long> Subscriptions_MaxSize = new PreferenceDefinition<long>(
            -1,
            "subscriptions.max_size",
            "Subscriptions:MaxSize",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// When videos are marked as watched, they are deleted automatically from disk.
        /// </summary>
        public static readonly PreferenceDefinition<bool> Subscriptions_AutoDeleteWatched = new PreferenceDefinition<bool>(
            true,
            "subscriptions.auto_delete_watched",
            "Subscriptions:AutoDeleteWatched",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Pattern indicating where files are downloaded automatically.
        /// </summary>
        public static readonly PreferenceDefinition<string> Subscriptions_DownloadPath = new PreferenceDefinition<string>(
            "{DownloadDirectory}/{FolderPath}/{Subscription.Name}/{Video.PlaylistIndex}-{Video.Name}",
            "subscriptions.download_path",
            "Subscriptions:DownloadPath",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Maximum number of downloaded videos to keep per user (-1 = no limit). This setting only applies to the automatic downloader, the user can download more videos than this limit. Use the User_CountQuota option for a hard limit.
        /// </summary>
        public static readonly PreferenceDefinition<int> User_MaxCount = new PreferenceDefinition<int>(
            10,
            "user.max_count",
            "User:MaxCount",
            null,
            PreferenceFlags.User
        );

        /// <summary>
        /// Maximum size a user's downloaded videos can take in MB (-1 = no limit). This setting only applies to the automatic downloader, the user can download more videos than this limit. Use the User_SizeQuota option for a hard limit.
        /// </summary>
        public static readonly PreferenceDefinition<long> User_MaxSize = new PreferenceDefinition<long>(
            -1,
            "user.max_size",
            "User:MaxSize",
            null,
            PreferenceFlags.User
        );

        /// <summary>
        /// Hard limit on numbers of downloaded videos a user can keep (-1 = no limit). Also applies to manual downloads.
        /// </summary>
        public static readonly PreferenceDefinition<int> User_CountQuota = new PreferenceDefinition<int>(
            -1,
            "user.count_quota",
            "User:CountQuota",
            null,
            PreferenceFlags.User
        );

        /// <summary>
        /// Hard limit on total size of downloaded videos a user can keep in MB (-1 = no limit). Also applies to manual downloads.
        /// </summary>
        public static readonly PreferenceDefinition<long> User_SizeQuota = new PreferenceDefinition<long>(
            -1,
            "user.size_quota",
            "User:SizeQuota",
            null,
            PreferenceFlags.User
        );

        /// <summary>
        /// Maximum download rate in bytes per second (e.g. 50K or 4.2M)
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_LimitRate = new PreferenceDefinition<string>(
            null,
            "ytdl.limit_rate",
            "Ytdl:LimitRate",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Number of retries (default is 10), or "infinite".
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_Retries = new PreferenceDefinition<string>(
            null,
            "ytdl.retries",
            "Ytdl:Retries",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write video description to a .description file.
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_WriteDescription = new PreferenceDefinition<bool>(
            false,
            "ytdl.write_description",
            "Ytdl:WriteDescription",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write video metadata to a .info.json file
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_WriteInfoJson = new PreferenceDefinition<bool>(
            false,
            "ytdl.write_info_json",
            "Ytdl:WriteInfoJson",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write thumbnail image to disk
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_WriteThumbnail = new PreferenceDefinition<bool>(
            false,
            "ytdl.write_thumbnail",
            "Ytdl:WriteThumbnail",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Contact the youtube-dl server for debugging
        /// </summary>
        public static readonly PreferenceDefinition<bool?> Ytdl_CallHome = new PreferenceDefinition<bool?>(
            null,
            "ytdl.call_home",
            "Ytdl:CallHome",
            null,
            0
        );

        /// <summary>
        /// Video format to download
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_Format = new PreferenceDefinition<string>(
            "bestvideo+bestaudio",
            "ytdl.format",
            "Ytdl:Format",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Download all possible formats
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_AllFormats = new PreferenceDefinition<bool>(
            false,
            "ytdl.all_formats",
            "Ytdl:AllFormats",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Prefer free video formats
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_PreferFreeFormats = new PreferenceDefinition<bool>(
            false,
            "ytdl.prefer_free_formats",
            "Ytdl:PreferFreeFormats",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// If a merge is required (e.g. bestvideo+bestaudio), output to given container format. One of mkv, mp4, ogg, webm, flv. Ignored if no merge is required.
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_MergeOutputFormat = new PreferenceDefinition<string>(
            "mp4",
            "ytdl.merge_output_format",
            "Ytdl:MergeOutputFormat",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write subtitle files
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_WriteSubtitles = new PreferenceDefinition<bool>(
            false,
            "ytdl.write_sub",
            "Ytdl:WriteSub",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write automatically generated subtitles (YouTube only)
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_WriteAutoSub = new PreferenceDefinition<bool>(
            false,
            "ytdl.write_auto_sub",
            "Ytdl:WriteAutoSub",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Write all available subtitles of the video
        /// </summary>
        public static readonly PreferenceDefinition<bool> Ytdl_AllSubs = new PreferenceDefinition<bool>(
            false,
            "ytdl.all_subs",
            "Ytdl:AllSubs",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Subtitle format, accepts formats preference, for example: "srt" or "ass/srt/best"
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_SubFormat = new PreferenceDefinition<string>(
            "best",
            "ytdl.sub_format",
            "Ytdl:SubFormat",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

        /// <summary>
        /// Languages of the subtitles to download (optional) separated by commas.
        /// </summary>
        public static readonly PreferenceDefinition<string> Ytdl_SubLang = new PreferenceDefinition<string>(
            "en",
            "ytdl.sub_lang",
            "Ytdl:SubLang",
            null,
            PreferenceFlags.User | PreferenceFlags.SubscriptionFolder | PreferenceFlags.Subscription
        );

    }
}