/* THIS FILE IS AUTOGENERATED DO NOT EDIT
 *
 * This file is autogenerated from Options.csv. 
 * If you want to add a new user interface coordinate 
 * do so in the CSV file then rebuild.
 */
using Regard.Model;

namespace Regard.Backend.Configuration
{
    public static class Options
    {
        /// <summary>
        /// Indicates if the first time setup was performed.
        /// </summary>
        public static readonly OptionDefinition<bool> Server_Initialized = new OptionDefinition<bool>(
            false,
            "server.initialized",
            null,
            null,
            0
        );

        /// <summary>
        /// Allow user registrations from the frontend.
        /// </summary>
        public static readonly OptionDefinition<bool> Server_AllowRegistrations = new OptionDefinition<bool>(
            true,
            "server.allow_registrations",
            "AllowRegistrations",
            "REGARD_ALLOW_REGISTRATIONS",
            0
        );

        /// <summary>
        /// Send debugging information to the frontend
        /// </summary>
        public static readonly OptionDefinition<bool> Server_Debug = new OptionDefinition<bool>(
            false,
            "server.debug",
            "Debug",
            "REGARD_DEBUG",
            0
        );

        /// <summary>
        /// If enabled, videos will be downloaded automatically
        /// </summary>
        public static readonly OptionDefinition<bool> Subscriptions_AutoDownload = new OptionDefinition<bool>(
            true,
            "subscriptions.auto_download",
            "Subscriptions:AutoDownload",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Order in which to download videos
        /// </summary>
        public static readonly OptionDefinition<VideoOrder> Subscriptions_DownloadOrder = new OptionDefinition<VideoOrder>(
            VideoOrder.Newest,
            "subscriptions.download_order",
            "Subscriptions:DownloadOrder",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Maximum number of downloaded videos to keep per subscription (-1 = no limit). This limit only applies to the automatic downloader, but the user can manually download more videos.
        /// </summary>
        public static readonly OptionDefinition<int> Subscriptions_MaxCount = new OptionDefinition<int>(
            3,
            "subscriptions.max_count",
            "Subscriptions:MaxCount",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Maximum size a subscription can take on disk in MB (-1 = no limit). This limit only applies to the automatic downloader, but the user can manually download more videos.
        /// </summary>
        public static readonly OptionDefinition<long> Subscriptions_MaxSize = new OptionDefinition<long>(
            -1,
            "subscriptions.max_size",
            "Subscriptions:MaxSize",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// When videos are marked as watched, they are deleted automatically from disk.
        /// </summary>
        public static readonly OptionDefinition<bool> Subscriptions_AutoDeleteWatched = new OptionDefinition<bool>(
            true,
            "subscriptions.auto_delete_watched",
            "Subscriptions:AutoDeleteWatched",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Pattern indicating where files are downloaded automatically.
        /// </summary>
        public static readonly OptionDefinition<string> Subscriptions_DownloadPath = new OptionDefinition<string>(
            "{DownloadDirectory}/{FolderPath}/{Subscription.Name}/{Video.PlaylistIndex}-{Video.Name}",
            "subscriptions.download_path",
            "Subscriptions:DownloadPath",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Maximum number of downloaded videos to keep per user (-1 = no limit). This setting only applies to the automatic downloader, the user can download more videos than this limit. Use the User_CountQuota option for a hard limit.
        /// </summary>
        public static readonly OptionDefinition<int> User_MaxCount = new OptionDefinition<int>(
            10,
            "user.max_count",
            "User:MaxCount",
            null,
            OptionFlags.User
        );

        /// <summary>
        /// Maximum size a user's downloaded videos can take in MB (-1 = no limit). This setting only applies to the automatic downloader, the user can download more videos than this limit. Use the User_SizeQuota option for a hard limit.
        /// </summary>
        public static readonly OptionDefinition<long> User_MaxSize = new OptionDefinition<long>(
            -1,
            "user.max_size",
            "User:MaxSize",
            null,
            OptionFlags.User
        );

        /// <summary>
        /// Hard limit on numbers of downloaded videos a user can keep (-1 = no limit). Also applies to manual downloads.
        /// </summary>
        public static readonly OptionDefinition<int> User_CountQuota = new OptionDefinition<int>(
            -1,
            "user.count_quota",
            "User:CountQuota",
            null,
            OptionFlags.User
        );

        /// <summary>
        /// Hard limit on total size of downloaded videos a user can keep in MB (-1 = no limit). Also applies to manual downloads.
        /// </summary>
        public static readonly OptionDefinition<long> User_SizeQuota = new OptionDefinition<long>(
            -1,
            "user.size_quota",
            "User:SizeQuota",
            null,
            OptionFlags.User
        );

        /// <summary>
        /// Maximum download rate in bytes per second (e.g. 50K or 4.2M)
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_LimitRate = new OptionDefinition<string>(
            null,
            "ytdl.limit_rate",
            "Ytdl:LimitRate",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Number of retries (default is 10), or "infinite".
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_Retries = new OptionDefinition<string>(
            null,
            "ytdl.retries",
            "Ytdl:Retries",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write video description to a .description file.
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_WriteDescription = new OptionDefinition<bool>(
            false,
            "ytdl.write_description",
            "Ytdl:WriteDescription",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write video metadata to a .info.json file
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_WriteInfoJson = new OptionDefinition<bool>(
            false,
            "ytdl.write_info_json",
            "Ytdl:WriteInfoJson",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write thumbnail image to disk
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_WriteThumbnail = new OptionDefinition<bool>(
            false,
            "ytdl.write_thumbnail",
            "Ytdl:WriteThumbnail",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Contact the youtube-dl server for debugging
        /// </summary>
        public static readonly OptionDefinition<bool?> Ytdl_CallHome = new OptionDefinition<bool?>(
            null,
            "ytdl.call_home",
            "Ytdl:CallHome",
            null,
            0
        );

        /// <summary>
        /// Video format to download
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_Format = new OptionDefinition<string>(
            "bestvideo[vcodec!*=av01]+bestaudio",
            "ytdl.format",
            "Ytdl:Format",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Download all possible formats
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_AllFormats = new OptionDefinition<bool>(
            false,
            "ytdl.all_formats",
            "Ytdl:AllFormats",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Prefer free video formats
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_PreferFreeFormats = new OptionDefinition<bool>(
            false,
            "ytdl.prefer_free_formats",
            "Ytdl:PreferFreeFormats",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// If a merge is required (e.g. bestvideo+bestaudio), output to given container format. One of mkv, mp4, ogg, webm, flv. Ignored if no merge is required.
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_MergeOutputFormat = new OptionDefinition<string>(
            "mp4",
            "ytdl.merge_output_format",
            "Ytdl:MergeOutputFormat",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write subtitle files
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_WriteSubtitles = new OptionDefinition<bool>(
            false,
            "ytdl.write_sub",
            "Ytdl:WriteSub",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write automatically generated subtitles (YouTube only)
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_WriteAutoSub = new OptionDefinition<bool>(
            false,
            "ytdl.write_auto_sub",
            "Ytdl:WriteAutoSub",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Write all available subtitles of the video
        /// </summary>
        public static readonly OptionDefinition<bool> Ytdl_AllSubs = new OptionDefinition<bool>(
            false,
            "ytdl.all_subs",
            "Ytdl:AllSubs",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Subtitle format, accepts formats preference, for example: "srt" or "ass/srt/best"
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_SubFormat = new OptionDefinition<string>(
            "best",
            "ytdl.sub_format",
            "Ytdl:SubFormat",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

        /// <summary>
        /// Languages of the subtitles to download (optional) separated by commas.
        /// </summary>
        public static readonly OptionDefinition<string> Ytdl_SubLang = new OptionDefinition<string>(
            "en",
            "ytdl.sub_lang",
            "Ytdl:SubLang",
            null,
            OptionFlags.User | OptionFlags.SubscriptionFolder | OptionFlags.Subscription
        );

    }
}