namespace Regard.Common.API.Model
{
    /// <summary>
    /// One selectable subtitle track for the player. Discovered from the sidecar files on disk, so it
    /// exists only for a downloaded video.
    /// </summary>
    public class ApiSubtitleTrack
    {
        /// <summary>Language tag as yt-dlp named the file ("en", "ro", "en-orig"). Used as the track id.</summary>
        public string Lang { get; set; }

        /// <summary>Display name for the picker, e.g. "Romanian (auto-generated)".</summary>
        public string Label { get; set; }

        /// <summary>
        /// True when the cues look machine-generated (sniffed from the file — yt-dlp gives manual and
        /// automatic captions identical names). Always false for .srt, where the conversion strips the
        /// evidence.
        /// </summary>
        public bool AutoGenerated { get; set; }
    }
}
